version: "3"
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: b2b
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
